export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';

export const BOOK_SEATS = 'BOOK_SEATS';
export const BOOK_SEATS_SUCCESS = 'BOOK_SEATS_SUCCESS';
export const BOOK_SEATS_FAIL = 'BOOK_SEATS_FAIL';

export const FETCH_USER_EVENTS = 'FETCH_USER_EVENTS';
export const FETCH_USER_EVENTS_SUCCESS = 'FETCH_USER_EVENTS_SUCCESS';
export const FETCH_USER_EVENTS_FAIL = 'FETCH_USER_EVENTS_FAIL';

export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAIL = 'CANCEL_BOOKING_FAIL';